<footer class="d-flex justify-content-center">
    <section class="d-flex align-items-center">
        <section class="block">
            <article class="d-flex justify-content-center">
               <a href="#" class="button">
                   <div class="icon">
                       <i class="fab fa-instagram"></i>
                   </div>
                   <span>Instagram</span>
                </a>
               <a href="#" class="button">
                   <div class="icon">
                       <i class="fab fa-facebook-f"></i>
                   </div>
                   <span>Facebook</span>
                </a>
               <a href="#" class="button">
                   <div class="icon">
                       <i class="fab fa-twitter"></i>
                   </div>
                   <span>Twitter</span>
                </a>
            </article>
           <article class="info">
               <p>&copy; 2023 Tora's Beef || Created by <a href=https://twitter.com/herhelloweb>JB Systens</a></p>
           </article>
           
        </section>
    </section>
</footer>
</body>