    <!DOCTYPE html>
    <html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Tora's Beef</title>
        <!--Icon-->
        <link rel="icon" href="">
        <!--Font Awesome-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <!--Bootstrap CSS-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <!--Bootstrap JS-->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <!--JQuery-->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <!--CSS-->
        <link rel="stylesheet" href="Midias/Style/css/style.css">
        <!--JS-->
        <script src="/Midias/Js/js.js"></script>
    </head>
    <body>
    <header class="navbar fixed-top navbar-expand-lg navbar-light row header">
            <section class="col-1">
                <a href="/" class="nav-link">
                    <img height="70px" width="110px" src="Midias/Imgs/logo.png" alt="Logo Tora's Beef">
                </a>
            </section>
            <section class="col-4">
                <h3 class="display-5 titulo">
                    <strong>Tora's Beef</strong>
                </h3>
            </section>
            <nav class="col-6 d-flex justify-content-end">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="/contato" class="d-flex align-items-center">
                            <h4>Contato</h4> 
                            <i class="fa-solid fa-phone"></i>
                        </a>
                        <div class="cobertura"></div>
                    </li>
                    <li class="nav-item">
                        <a href="/pedido" class="d-flex align-items-center">
                            <h4>Fazer pedido</h4> 
                            <i class="fa-solid fa-truck-fast"></i>
                        </a>
                        <div class="cobertura"></div>
                    </li>
                </ul>
            </nav>
        </header>
        